### ISSUE TITLE
Mention CONTRIBUTING.md

### ISSUE THREAD

**Issue by bast** [coderefinery/social-coding#16]
Explain what typically goes in there, why this is good to have, and link to an example or two which can be used as inspiration.

**Comment by annefou** [comment]
I think we should also show CODE OF CONDUCT too. 
Having README, CONTRIBUTING guidelines and a CODE OF CONDUCT are the minimum you need to have to get contributions.

**Comment by bast** [comment]
Yes, fully agree. Too few codes have this. Also too few of my codes :-)

**Comment by annefou** [comment]
The example given as part of Mozilla Open Leader training is
https://github.com/KirstieJane/STEMMRoleModels
