### ISSUE TITLE
Mention FAIR

### ISSUE THREAD

**Issue by bast** [coderefinery/social-coding#2]
Not only FAIR data but also discuss FAIR in the context of software.

**Comment by wikfeldt** [comment]
there's a discussion of FAIR in the context of software in the 4OSS lesson material which is currently being developed. Maybe that can be referenced:
https://github.com/SoftDev4Research/4OSS-lesson/blob/gh-pages/_episodes/01-introduction.md

**Comment by bast** [comment]
Very interesting and relevant - thanks!
