### ISSUE TITLE
review learning objectives

### ISSUE THREAD

**Issue by mehimself** [coderefinery/social-coding#32]
These are notes from the Instructor training WS in Stockholm dec. 2019

# learning objectives
What learning objectives should "social coding" aim at?
 - motivation
   - exercise: evaluate a showcase example of a repository reflecting our lessons. 
     - will it motivate novices?
     - reproducible research first? 
   - how can your code lifetime be extended beyond the scope of your projects?
     - how to form communities around it? Who has which responsibilities on it?
   - how do you ensure you are credited for your work?
   - others can improve your code
 - where to ask what questions about licensing?
   - EU law > domestic law > institutional implementations
   - do not appear to give legal advice (illegal, quickly outdated)
 - license compatibility
 - exercise on choosing a repo to reuse
   - what do you look at in new repos: repository quality assessment 

# sharing
 - "share with your future self". fx: changing employer (keeping access to your code through open source licenses) 
 - CC-0 is trumped by Ophavsret/Urheberrecht
  - CC-BY is minimal license
  - review licensing restrictions in nordic states
  - what are patent rights in nordic countries
  - considerations for the practice of copying

**Comment by bast** [comment]
This is now almost 3 years old. Hopefully we have incorporated these now in the lesson iterations.
