### ISSUE TITLE
reason for opening: discourage competitors

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/social-coding#34]
I was just in a discussion about value of opening models.  Someone pointed out that others have realized that "openness discourage competitors".  If others can't build on your work, they will make competing work, which usually can be done easily.  Then you lose your leadership position.  You may not open right away, but eventually you will feel the pressure.

This is obvious, but I've never seen it said so clearly (in CR or otherwise).

**Comment by bast** [comment]
Great point!
