### ISSUE TITLE
Feedback from CodeRefinery/INES hackathon

### ISSUE THREAD

**Issue by annefou** [coderefinery/social-coding#35]
- To apply the concept we teach for actual project, some guidelines on how to write proper CONTRIBUTING.md, README.md, etc. could be useful (could have associated exercises too).

- We used https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/ for some parts but jungling between two different source of information is not always straightforward. 

So it would be nice to complement this lesson with exercises on either existing project (attendee's project) or on new project.  I have the feeling that many would benefit from applying ot to their own project.

**Comment by bast** [comment]
It would be a really useful exercise to apply this to own projects and then discuss the difficulties or questions with others.

**Comment by bast** [comment]
I think we have now links to good resources. It would be nice to have exercises also but for the moment we go with hackmd-discussion engagement instead of group exercises to also include stream participants.
