### ISSUE TITLE
Is sharing a container "sharing software"

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/social-coding#43]
If a "docker image" is shared  can that attribute to  software-sharing ?

**Comment by bast** [comment]
In my understanding yes. Probably this is considered redistributing in binary form but it's still redistributing.

**Comment by Sabryr** [comment]
"redistributing" and "sharing" are they the same thing ? how can I contribute to a binary distribution on a container. 
If I get the container and perfome the development inside it using the existing binary  and recreate a "derived" container, is that good practice.  Note to self: check licensing for containers
