### ISSUE TITLE
Suggestion: license in, license out

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/social-coding#5]
I got this catchphrase from a collegue at Aalto.  It originally applied to copyright, but the overall idea applies, too.  I think we can structure somewhat around the concept of "you want to use what others have done, and you want others to be able to use from you".  They are symmetric and we perhaps go by topic, talk about what you are allowed to use, and then how you can make your stuff usable by others.  Quick mock-up attached.

I will have more suggestions shortly (I hope), which we can discuss in person.

![in-out](https://user-images.githubusercontent.com/6877977/48515822-8035ff80-e86a-11e8-83d1-41a5f3823dfb.png)

**Comment by bast** [comment]
This suggestion is already in `master`. Closing.
