### ISSUE TITLE
point out more, only certain licenses let you keep using when you change jobs

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/social-coding#51]
This was a comment from the stream HackMD.  We do briefly mention "this collaborator could be you in a future job", but this could be a major point to consider.

**Comment by samumantha** [comment]
So to everyone who had this problem/has considered this: Which license would/could/did you choose and why?

**Comment by matuskalas** [comment]
Is this a question of license, or rather also authorship (© ownership in common law | English-speaking countries) itself?

I guess if you're an author and you get agreement from all the other authors, you can change the license as you wish.

And if the license is open source (any open source license), you can use & distribute both unmodified and modified versions even if you're not an author.

**Comment by bast** [comment]
As to which license, for me: MIT or BSD for very small things where it does not matter to me whether improvements are shared, MPL or LGPL or AGPL for code where I would like to make sure that improvements are shared, GPL if I "have to" or if I want to make sure that everything is shared.

**Comment by Sabryr** [comment]
Is this something we should mention explicitly, @rkdarst was you intention to mention during license types ?
