### ISSUE TITLE
Integrate slides into sphinx lesson material

### ISSUE THREAD

**Issue by samumantha** [coderefinery/social-coding#58]
When working through the material I noticed that there is a lot of slides, texts and information for the 75 min including break time in the workshop.
So this is a suggestion to have full text material as 'normal sphinx lesson' and then a shorter slideset to present with less text, see also here: https://coderefinery.zulipchat.com/#narrow/stream/136238-lessons/topic/social.20coding.20lesson
You can see a basic draft of how the lesson could look like here : https://github.com/samumantha/sc_test/tree/sphinxiphy
This is only the content of slides transformed into sphinx lesson with the sphinx lesson template.
For having it as material, some more adjustments will need to be made. But first I wanted to ask your opinion on this (making the initial draft was good practice and not much work, so no worries if you think this is not needed). 

So, what do you think, should I continue with this?

**Comment by bast** [comment]
Is the draft also rendered somewhere or should we preview locally?

**Comment by annefou** [comment]
Fantastic! Yes moving from slides would make it easier to integrate exercises in the social coding lesson. Thank you!!!

**Comment by bast** [comment]
I previewed locally and I think this will indeed be more practical than a slide-deck for exercises and also allow to put in instructor notes "inline" which don't work well in a slide format.

Also in reality it seems it is easier for a speaker to skip a box in a Sphinx lesson than to skip a slide and the "skippability" is important to not rush through.

I also agree that there were way too many slides so making this more exercise-centric is a good move.

**Comment by samumantha** [comment]
Thanks for the feedback, then I will create a draft pull request and update a bit more towards more lesson style texts. Will let you know when there is more to review or post issues with open questions/ new suggestions

**Comment by annefou** [comment]
Not sure why it did not close this issue.
