### ISSUE TITLE
make check your understanding boxes with solutions

### ISSUE THREAD

**Issue by samumantha** [coderefinery/social-coding#65]
Idea (with @annefou ):
All exercise boxes that exist at the moment could become check your understanding boxes in the end of lessons with solutions added. 
Not to be done in class but in participants own time, therefore we need to offer solutions or at least a thought.

**Comment by samumantha** [comment]
No, I think only the other lessons exercises. Unless you have an idea. But maybe the other ones first with a solution box?

**Comment by annefou** [comment]
Yes. Sounds good! I just thought I missed something...
