### ISSUE TITLE
derivative work discussion to examples

### ISSUE THREAD

**Issue by samumantha** [coderefinery/social-coding#70]
idea (with @annefou )
remove discussion and write examples based on discussion points with thoughts.

Which of these is derivative work?

- [x]  Download some code from a website and add on to it
- [x]  Download some code and use a function in your code
- [x]  Changing the code
- [x]  Extending the code
- [x]  Completely rewriting the code
- [x]  Rewriting the code to a different programming language
- [ ]  Linking to libraries (static or dynamic), plug-ins, and drivers
- [ ]  Clean room design (somebody explains you the code but you have never seen it)
- [ ]  You read a paper, understand algorithm, write own code

**Comment by annefou** [comment]
Nobody is assigned to this issue. Shall I take it?

**Comment by samumantha** [comment]
I can take it, you already have so many ;)
