### ISSUE TITLE
make the lesson flow

### ISSUE THREAD

**Issue by samumantha** [coderefinery/social-coding#71]
current setup worked well for slides, as lesson material it may need some better flow.

Ideas on how to do this are very welcome :)

**Comment by Sabryr** [comment]
@samumantha do you have some idea about this now or waiting for input ? what do you think of a lifecycle diagram for software code

**Comment by samumantha** [comment]
Currently no ideas and not working on it. Assignments were leftover from last course. Sorry if this caused confusion

**Comment by bast** [comment]
I am closing this because it is not really clear how to solve it but as I am now going through lesson and preparing, I will hopefully arrive at better lesson flow.
