### ISSUE TITLE
Once the lesson is up, please adapt links

### ISSUE THREAD

**Issue by bast** [coderefinery/social-coding#74]
- https://coderefinery.org/lessons/
- https://coderefinery.github.io/2021-05-10-workshop/

**Comment by samumantha** [comment]
How can I see which link needs to be put there?

**Comment by bast** [comment]
I meant replace cicero... link by https://coderefinery.github.io/social-coding/

**Comment by annefou** [comment]
Done (and multiple PR because I did not look carefully!). So I think we can close this issue too.
