### ISSUE TITLE
Add headers to exercises

### ISSUE THREAD

**Issue by samumantha** [coderefinery/social-coding#80]
we noticed that if there is no header ## Ecercise or similar in front (does within exercise box work as well?) of exercise boxes , they cannot be linked. 

For linking the exercises on the hackmd having links directly to exercises will help, so we should probably add headers to every exercise to make this possible.

Is there maybe also another way to do this?

**Comment by bast** [comment]
Also make sure all exercises show up in the exercise overview, correctly formatted.
