### ISSUE TITLE
feedback from studyGroup@UiO

### ISSUE THREAD

**Issue by annefou** [coderefinery/social-coding#9]
We went through this lesson as part of the studyGroup@UiO (2 hours). This idea was to teach the trainer so we can reuse this lesson in future workshops. 

Here are some suggestions (open to discusions...):

- [x] Add a link to the github repository https://github.com/coderefinery/social-coding, for instance on the last slide to encourage contributions
- [x] Add a LICENSE file in the github repository as suggested in slide 34 (licensing)
- [x] slide 8:  maybe we could add a note to make sure the sentence "In practice almost nobody will care/judge." is related to the code quality and not the code itseld. For instance replacing it by "In practice almost nobody will judge the quality of your code.". We thought the sentence could be mis-interpreted.
- [x] Reproducibility - generally speaking: "Make it possible to reproduce your results 10 years later". It should be an aim but in practice it is often not possible. 
- [x] slide 12:  **Document dependencies with versions (use Pipenv in Python projects)**: example (using pipenv) is too narrow. Maybe add another example (using conda package manager or something similar) that can apply to different programming languages.

**Share your data (in Norway e.g. using https://dataverse.no)**: same comment as in the previous PR. add other example as dataverse.no is not in use in Oslo.

- [x] we would skipp slides 15 and 16 as we found them too detailed. Saying that using a version control is good but details should be part of a separate git lesson.

- [x] in the list of possible license,  CC-BY-SA-4.0 and similar should be mentioned and explained too. We found weird that the license used in the lesson is not explained.

- [x] slide 35: maybe mention that choosealicense can be used to add your license file in your github repository (via an "automatic pull request").
- [x] slide 39:  add information on how to get free github repository (private) for education/research and as a use case we could advertise the move from private to public when you are ready. It is a bit controversial (as the goal should be to be fully open from the beginning) but it may help convincing researchers to use git.

**Comment by bast** [comment]
Thank you for the very useful feedback! I will try to bring it in very quickly before the material changes too much with 1-2 pending PRs.

**Comment by bast** [comment]
I am checking off issues which have either been solved or which have been taken out as a standalone issue for follow-up.

**Comment by bast** [comment]
About choosealicense and automatic pull requests: wow I did not know! Nice!

**Comment by bast** [comment]
All are now either solved or followed-up in micro-issues. Thanks again!
