### ISSUE TITLE
Add guidance on how to cite software

### ISSUE THREAD

**Issue by samumantha** [coderefinery/social-coding#90]
Not all software has doi, docs or a publication that describes the software, so it sometimes is not quite clear what and how to cite it. 

There could be a section that goes through the necessary information when citing software for giving credit to the developers and making the own workflow reproducible (ie version,..).

See eg:
http://www.ijdc.net/index.php/ijdc/article/view/11.2.48 
https://www.software.ac.uk/how-cite-software?_ga=1.54830891.1882560887.1489012280

**Comment by bast** [comment]
Done in 343205f09bd09bda80cf.
